client/src/intro-exit/CheckUnderstanding.jsx
client/src/intro-exit/EnterNickname.jsx
client/src/intro-exit/Introduction.jsx
client/src/intro-exit/VideoCheck.jsx

Made intro steps more cohesive by unifying styling

Intro step styling

---

client/src/App.jsx
client/src/components/SurveyWrapper.css
client/src/components/SurveyWrapper.jsx
client/src/intro-exit/Surveys/quality_control.json
client/src/intro-exit/Surveys/quality_control.jsx
client/src/intro-exit/Surveys/team_viability.json
client/src/intro-exit/Surveys/team_viability.jsx

Hard-coded in the team-viability and QC surveys

Skylar exit surveys

---

.empirica/treatments.yaml
client/src/components/VideoCall.jsx
client/src/pages/Discussion.jsx
cypress/e2e/No_Experiments_Available.js

Treatments variable for removing jitsi features

---

server/src/callbacks.mjs

Move topic fetch to onNewBatch

---

server/src/callbacks.mjs

For now this just logs every time the a new player joins. Let me know if this is good enough for now or if I should do something more complex.
https://github.com/Watts-Lab/deliberation-project/issues/49

Track participant arrivals

---

client/src/intro-exit/VideoCheck.jsx
cypress/e2e/Normal_Paths.js

Update checkbox logic

---

Dockerfile
Dockerfile.dev
cypress/e2e/01_Normal_Paths.js
push_data.sh

uses github api to push data from digitalocean deploy to private data repo

James push data

---

client/src/Stage.jsx
client/src/intro-exit/Surveys/quality_control.jsx
server/src/callbacks.mjs

Fix payment display

---

client/src/components/Alert.jsx
client/src/intro-exit/CheckUnderstanding.jsx
client/src/intro-exit/VideoCheck.jsx
cypress/e2e/01_Normal_Paths.js
cypress/e2e/01b_Normal_Paths_Icebreaker.js
cypress/e2e/01c_Normal_Paths_TrainingVideo.js
cypress/e2e/02_Batch_Canceled.js
cypress/e2e/03_Games_Filled.js
cypress/e2e/06_Multiplayer_Normal_Paths_Icebreaker.js
cypress/e2e/07_EyesOn_Check.js

There are now some errors at the end of the cypress tests that are related to logging back into Admin?

Skylar-Alerts

---

.empirica/treatments.yaml
client/src/App.jsx
client/src/components/Topic.jsx
client/src/intro-exit/BetaVideoConsent.jsx
client/src/intro-exit/VideoCheck.jsx

- saves player choice to attribute "videoConsent", where true means consents, and false refuses
- stage placed after understanding check before nickname
Please check that styling and wording meets requirements.
Tested locally that variable saves correctly to tajriba.json, and both buttons leads to next stage.

Add Video Consent Intro for Beta

---

client/index.html
client/src/components/Button.jsx
client/src/main.jsx

Fixed feedback button to top right. (Top left inteferes with page titles)

Feedback button

---

.eslintrc
client/index.html
client/src/App.jsx
client/src/components/Alert.jsx
client/src/components/Topic.jsx
client/src/intro-exit/CheckUnderstanding.jsx
cypress/e2e/00_Naked_URL.js
cypress/e2e/01_Normal_Paths.js
cypress/e2e/06_Multiplayer_Normal_Paths_Icebreaker.js

Also added some eslint rules to ignore unresolved dependencies (lots of those as we don't maintain a local `node_modules` folder) and to ignore use of console logs on the client side (which we're using for cypress, but there may be better patterns for?)

Fix bug when playerKey is not present in URL

---

client/index.html
client/src/components/Topic.jsx

Closes https://github.com/Watts-Lab/deliberation-empirica/issues/223
(or at least attempts to).

James fix form submit

---

README.md
client/index.html

-a flag to remove all containers, images, and networks not in use. --volumes to also remove volumes not in use.

update prune command

---

client/src/components/Timer.jsx
client/src/pages/TrainingVideo.jsx

disabled pointer interaction with video graphics element using CSS.
#288

Prevent Mouse Interaction with Training Video

---

client/src/Stage.jsx
client/src/components/HairCheck.jsx
client/src/pages/Discussion.jsx
client/src/pages/Prompt.jsx
client/src/pages/TrainingVideo.css
client/src/pages/TrainingVideo.jsx

- Aspect-ratio fix on training video display
- displaying discussion video and prompt side by side
- reassigning flex so that video and prompt given equal width
- temporarily disabled speaker selection since functionality nonexistent

Fixed layout of several components

---

README.md
client/src/components/HairCheck.jsx

Wrapped DailyCallObject in React state.
Now able to control all track changes through Daily and get updated tracks through Daily.

Fix Haircheck

---

.empirica/treatments.yaml
client/src/components/RadioGroup.jsx
client/src/pages/Prompt.jsx
cypress/support/sharedSteps.js

fixes https://github.com/Watts-Lab/deliberation-empirica/issues/341

fix radiogroup name issue

---

Dockerfile
Dockerfile.dev
client/package.json
cypress/support/sharedSteps.js
server/package.json
server/src/exportScienceData.js
server/src/getTreatments.js

closes https://github.com/Watts-Lab/deliberation-topics/issues/27
closes https://github.com/Watts-Lab/deliberation-topics/issues/26
starts to work on https://github.com/Watts-Lab/deliberation-empirica/issues/407 but this still wants some visualization to go even further, I think...

Validate treatment files and prompt files

---

HIT_description2.html
client/src/intro-exit/Debrief.jsx
client/src/intro-exit/DescriptivePlayerIdForm.jsx
client/src/intro-exit/IntegratedConsent.jsx

Addresses changes listed in https://github.com/willschulz/bad-influence/issues/6

pre-pilot changes

---

client/src/components/TextArea.jsx
client/src/intro-exit/DescriptivePlayerIdForm.jsx
client/src/intro-exit/EnterNickname.jsx

autocomplete

---

.github/workflows/cypress.yml
README.md
cypress/e2e/01_Normal_Paths_Omnibus.js
cypress/fixtures/mockCDN/projects/example/README.md
cypress/runner.sh
entrypoint.sh
package.json
server/src/callbacks.js
server/src/exportParticipantData.js
server/src/exportPaymentData.js
server/src/exportScienceData.js
server/src/getTreatments.js
server/src/github.js
server/src/index.js
server/src/meetingRoom.js
server/src/qualtricsFetch.js
server/src/utils.js

working towards https://github.com/Watts-Lab/deliberation-empirica/issues/553

updata data save directory

---

server/src/callbacks.js
server/src/github.js

Avoid duplicating pushes to github
make error handling more robust

fix github push issue

---

cypress/e2e/07_Returning_Player.js
server/src/exportParticipantData.js

Addresses https://github.com/Watts-Lab/deliberation-empirica/issues/583

James debug no participant

---

client/package-lock.json
client/package.json
client/src/components/HairCheck.jsx
client/src/components/VideoCall.jsx
client/src/intro-exit/AttentionCheck.jsx
client/vite.config.js
cypress/e2e/01_Normal_Paths_Omnibus.js
cypress/fixtures/mockCDN/projects/example/cypress.treatments.yaml
cypress/fixtures/mockCDN/projects/example/demo.config.json
cypress/fixtures/mockCDN/projects/example/demo.treatments.yaml
cypress/fixtures/mockCDN/projects/example/multipleChoiceColorsMultiselect.md
server/src/getTreatments.js

Maybe addresses https://github.com/Watts-Lab/deliberation-empirica/issues/919, need to check

Update Hair Check to daily react hooks

---

client/package-lock.json
client/package.json
client/src/components/CheckboxGroup.jsx
cypress/e2e/01_Normal_Paths_Omnibus.js

Weird build failure:
https://github.com/Watts-Lab/deliberation-empirica/actions/runs/11900075695/job/33205037403

bump vite to resolve weirdo import issues

---

client/src/components/VideoCall.jsx
server/src/postFlight/exportScienceData.js
server/src/utils/comparison.js

fixes: https://github.com/Watts-Lab/deliberation-empirica/issues/932
also removes some annoying console logs I put in for debugging

update videocall to use react hook for daily iframe

---

client/src/App.jsx
client/src/components/HairCheck.jsx
client/src/components/IdleProvider.jsx
client/src/elements/Discussion.jsx
client/src/elements/TrainingVideo.jsx
client/src/intro-exit/Countdown.jsx
client/src/intro-exit/Debrief.jsx
client/src/intro-exit/EquipmentCheck.jsx
client/src/intro-exit/NoGames.jsx
server/src/postFlight/exportScienceData.js

closes: https://github.com/Watts-Lab/deliberation-empirica/issues/945

Idle detection and popup

---

client/package-lock.json
client/package.json
client/src/elements/Qualtrics.jsx
client/src/intro-exit/Consent.jsx
client/src/intro-exit/Lobby.jsx
server/src/preFlight/validateBatchConfig.ts

also deliberationId as a parameter for qualtrics

custom consent

---

client/src/elements/Prompt.jsx
cypress/e2e/01_Normal_Paths_Omnibus.js
server/src/preFlight/validateTreatmentFile.ts

- Added test case to check that shuffle order is preserved on re-render; reloading requires extra functionality
- Changes to Prompt.jsx to handle previewing in VSCode extension
Closes #983

Rerendering test case + Prompt.jsx changes

---

docs/templates.md
server/src/preFlight/validateTreatmentFile.ts

- Added explanation to docs to explain new contentType field in templates
- Added 'other' contentType value for custom templateContent usage for users
- Added indentation errors in diagnostics using parseDocument yaml parser's error object
Fixes: #982, #981 , #980

Doc updates

---

client/src/Stage.jsx
client/src/elements/Element.jsx
client/src/elements/Prompt.jsx

Editing Prompt file to remove error handling (error handling happens in Deliberation Lab Tools)
Closes #989

Edits for stage rendering
